allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
blockExoticSubdeps: true
minimumReleaseAge: 2880
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
