/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChaptersRouteImport } from './routes/_chapters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChaptersPreloadingRouteImport } from './routes/_chapters.preloading'
import { Route as ChaptersPaginationRouteImport } from './routes/_chapters.pagination'
import { Route as ChaptersLiveQueryFiltersRouteImport } from './routes/_chapters.live-query-filters'
import { Route as ChaptersLiveQueryRouteImport } from './routes/_chapters.live-query'
import { Route as ChaptersIntentPreloadingRouteImport } from './routes/_chapters.intent-preloading'
import { Route as ChaptersFiltersRouteImport } from './routes/_chapters.filters'
import { Route as ChaptersDebouncedPreloadFiltersRouteImport } from './routes/_chapters.debounced-preload-filters'
import { Route as ChaptersBasicRouteImport } from './routes/_chapters.basic'
import { Route as ApiShapesTypesRouteImport } from './routes/api/shapes/types'
import { Route as ApiShapesPokemonTypesRouteImport } from './routes/api/shapes/pokemon-types'
import { Route as ApiShapesPokemonRouteImport } from './routes/api/shapes/pokemon'

const ChaptersRoute = ChaptersRouteImport.update({
  id: '/_chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersPreloadingRoute = ChaptersPreloadingRouteImport.update({
  id: '/preloading',
  path: '/preloading',
  getParentRoute: () => ChaptersRoute,
} as any)
const ChaptersPaginationRoute = ChaptersPaginationRouteImport.update({
  id: '/pagination',
  path: '/pagination',
  getParentRoute: () => ChaptersRoute,
} as any)
const ChaptersLiveQueryFiltersRoute =
  ChaptersLiveQueryFiltersRouteImport.update({
    id: '/live-query-filters',
    path: '/live-query-filters',
    getParentRoute: () => ChaptersRoute,
  } as any)
const ChaptersLiveQueryRoute = ChaptersLiveQueryRouteImport.update({
  id: '/live-query',
  path: '/live-query',
  getParentRoute: () => ChaptersRoute,
} as any)
const ChaptersIntentPreloadingRoute =
  ChaptersIntentPreloadingRouteImport.update({
    id: '/intent-preloading',
    path: '/intent-preloading',
    getParentRoute: () => ChaptersRoute,
  } as any)
const ChaptersFiltersRoute = ChaptersFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => ChaptersRoute,
} as any)
const ChaptersDebouncedPreloadFiltersRoute =
  ChaptersDebouncedPreloadFiltersRouteImport.update({
    id: '/debounced-preload-filters',
    path: '/debounced-preload-filters',
    getParentRoute: () => ChaptersRoute,
  } as any)
const ChaptersBasicRoute = ChaptersBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => ChaptersRoute,
} as any)
const ApiShapesTypesRoute = ApiShapesTypesRouteImport.update({
  id: '/api/shapes/types',
  path: '/api/shapes/types',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesPokemonTypesRoute = ApiShapesPokemonTypesRouteImport.update({
  id: '/api/shapes/pokemon-types',
  path: '/api/shapes/pokemon-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesPokemonRoute = ApiShapesPokemonRouteImport.update({
  id: '/api/shapes/pokemon',
  path: '/api/shapes/pokemon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic': typeof ChaptersBasicRoute
  '/debounced-preload-filters': typeof ChaptersDebouncedPreloadFiltersRoute
  '/filters': typeof ChaptersFiltersRoute
  '/intent-preloading': typeof ChaptersIntentPreloadingRoute
  '/live-query': typeof ChaptersLiveQueryRoute
  '/live-query-filters': typeof ChaptersLiveQueryFiltersRoute
  '/pagination': typeof ChaptersPaginationRoute
  '/preloading': typeof ChaptersPreloadingRoute
  '/api/shapes/pokemon': typeof ApiShapesPokemonRoute
  '/api/shapes/pokemon-types': typeof ApiShapesPokemonTypesRoute
  '/api/shapes/types': typeof ApiShapesTypesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic': typeof ChaptersBasicRoute
  '/debounced-preload-filters': typeof ChaptersDebouncedPreloadFiltersRoute
  '/filters': typeof ChaptersFiltersRoute
  '/intent-preloading': typeof ChaptersIntentPreloadingRoute
  '/live-query': typeof ChaptersLiveQueryRoute
  '/live-query-filters': typeof ChaptersLiveQueryFiltersRoute
  '/pagination': typeof ChaptersPaginationRoute
  '/preloading': typeof ChaptersPreloadingRoute
  '/api/shapes/pokemon': typeof ApiShapesPokemonRoute
  '/api/shapes/pokemon-types': typeof ApiShapesPokemonTypesRoute
  '/api/shapes/types': typeof ApiShapesTypesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_chapters': typeof ChaptersRouteWithChildren
  '/_chapters/basic': typeof ChaptersBasicRoute
  '/_chapters/debounced-preload-filters': typeof ChaptersDebouncedPreloadFiltersRoute
  '/_chapters/filters': typeof ChaptersFiltersRoute
  '/_chapters/intent-preloading': typeof ChaptersIntentPreloadingRoute
  '/_chapters/live-query': typeof ChaptersLiveQueryRoute
  '/_chapters/live-query-filters': typeof ChaptersLiveQueryFiltersRoute
  '/_chapters/pagination': typeof ChaptersPaginationRoute
  '/_chapters/preloading': typeof ChaptersPreloadingRoute
  '/api/shapes/pokemon': typeof ApiShapesPokemonRoute
  '/api/shapes/pokemon-types': typeof ApiShapesPokemonTypesRoute
  '/api/shapes/types': typeof ApiShapesTypesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basic'
    | '/debounced-preload-filters'
    | '/filters'
    | '/intent-preloading'
    | '/live-query'
    | '/live-query-filters'
    | '/pagination'
    | '/preloading'
    | '/api/shapes/pokemon'
    | '/api/shapes/pokemon-types'
    | '/api/shapes/types'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basic'
    | '/debounced-preload-filters'
    | '/filters'
    | '/intent-preloading'
    | '/live-query'
    | '/live-query-filters'
    | '/pagination'
    | '/preloading'
    | '/api/shapes/pokemon'
    | '/api/shapes/pokemon-types'
    | '/api/shapes/types'
  id:
    | '__root__'
    | '/'
    | '/_chapters'
    | '/_chapters/basic'
    | '/_chapters/debounced-preload-filters'
    | '/_chapters/filters'
    | '/_chapters/intent-preloading'
    | '/_chapters/live-query'
    | '/_chapters/live-query-filters'
    | '/_chapters/pagination'
    | '/_chapters/preloading'
    | '/api/shapes/pokemon'
    | '/api/shapes/pokemon-types'
    | '/api/shapes/types'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChaptersRoute: typeof ChaptersRouteWithChildren
  ApiShapesPokemonRoute: typeof ApiShapesPokemonRoute
  ApiShapesPokemonTypesRoute: typeof ApiShapesPokemonTypesRoute
  ApiShapesTypesRoute: typeof ApiShapesTypesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chapters': {
      id: '/_chapters'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chapters/preloading': {
      id: '/_chapters/preloading'
      path: '/preloading'
      fullPath: '/preloading'
      preLoaderRoute: typeof ChaptersPreloadingRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/_chapters/pagination': {
      id: '/_chapters/pagination'
      path: '/pagination'
      fullPath: '/pagination'
      preLoaderRoute: typeof ChaptersPaginationRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/_chapters/live-query-filters': {
      id: '/_chapters/live-query-filters'
      path: '/live-query-filters'
      fullPath: '/live-query-filters'
      preLoaderRoute: typeof ChaptersLiveQueryFiltersRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/_chapters/live-query': {
      id: '/_chapters/live-query'
      path: '/live-query'
      fullPath: '/live-query'
      preLoaderRoute: typeof ChaptersLiveQueryRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/_chapters/intent-preloading': {
      id: '/_chapters/intent-preloading'
      path: '/intent-preloading'
      fullPath: '/intent-preloading'
      preLoaderRoute: typeof ChaptersIntentPreloadingRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/_chapters/filters': {
      id: '/_chapters/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof ChaptersFiltersRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/_chapters/debounced-preload-filters': {
      id: '/_chapters/debounced-preload-filters'
      path: '/debounced-preload-filters'
      fullPath: '/debounced-preload-filters'
      preLoaderRoute: typeof ChaptersDebouncedPreloadFiltersRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/_chapters/basic': {
      id: '/_chapters/basic'
      path: '/basic'
      fullPath: '/basic'
      preLoaderRoute: typeof ChaptersBasicRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/api/shapes/types': {
      id: '/api/shapes/types'
      path: '/api/shapes/types'
      fullPath: '/api/shapes/types'
      preLoaderRoute: typeof ApiShapesTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/pokemon-types': {
      id: '/api/shapes/pokemon-types'
      path: '/api/shapes/pokemon-types'
      fullPath: '/api/shapes/pokemon-types'
      preLoaderRoute: typeof ApiShapesPokemonTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/pokemon': {
      id: '/api/shapes/pokemon'
      path: '/api/shapes/pokemon'
      fullPath: '/api/shapes/pokemon'
      preLoaderRoute: typeof ApiShapesPokemonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChaptersRouteChildren {
  ChaptersBasicRoute: typeof ChaptersBasicRoute
  ChaptersDebouncedPreloadFiltersRoute: typeof ChaptersDebouncedPreloadFiltersRoute
  ChaptersFiltersRoute: typeof ChaptersFiltersRoute
  ChaptersIntentPreloadingRoute: typeof ChaptersIntentPreloadingRoute
  ChaptersLiveQueryRoute: typeof ChaptersLiveQueryRoute
  ChaptersLiveQueryFiltersRoute: typeof ChaptersLiveQueryFiltersRoute
  ChaptersPaginationRoute: typeof ChaptersPaginationRoute
  ChaptersPreloadingRoute: typeof ChaptersPreloadingRoute
}

const ChaptersRouteChildren: ChaptersRouteChildren = {
  ChaptersBasicRoute: ChaptersBasicRoute,
  ChaptersDebouncedPreloadFiltersRoute: ChaptersDebouncedPreloadFiltersRoute,
  ChaptersFiltersRoute: ChaptersFiltersRoute,
  ChaptersIntentPreloadingRoute: ChaptersIntentPreloadingRoute,
  ChaptersLiveQueryRoute: ChaptersLiveQueryRoute,
  ChaptersLiveQueryFiltersRoute: ChaptersLiveQueryFiltersRoute,
  ChaptersPaginationRoute: ChaptersPaginationRoute,
  ChaptersPreloadingRoute: ChaptersPreloadingRoute,
}

const ChaptersRouteWithChildren = ChaptersRoute._addFileChildren(
  ChaptersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChaptersRoute: ChaptersRouteWithChildren,
  ApiShapesPokemonRoute: ApiShapesPokemonRoute,
  ApiShapesPokemonTypesRoute: ApiShapesPokemonTypesRoute,
  ApiShapesTypesRoute: ApiShapesTypesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
