import createFetchClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const $pokeFetchClient = createFetchClient<paths>({
	baseUrl: "https://pokeapi.co/",
});
