import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: "https://pokeapi.co/api/v2/",
});
export const $pokeApiClient = createClient(fetchClient);
